<?php
namespace Sputnik\BlogBundle\DependencyInjection;


use App\Service\YamlLoader;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Extension\Extension;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Loader;


class SputnikBlogBundleExtension extends Extension
{
    public function getAlias()
    {
        return parent::getAlias(); // TODO: Change the autogenerated stub
    }

    public function getConfiguration(array $config, ContainerBuilder $container)
    {
        return parent::getConfiguration($config, $container); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $configs
     * @param ContainerBuilder $container
     * @throws \Exception
     */
    public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = $this->getConfiguration($configs, $container);
        $this->processConfiguration($configuration, $configs);

        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('routes.yaml');
    }


}